#!/bin/bash
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -c 3
#SBATCH --mem-per-cpu=32768
#SBATCH --gres=gpu:1
#SBATCH -t 120:00:00
#SBATCH --partition=critical
#SBATCH -A tukw-critical
#SBATCH --exclude=ai_gpu[26-35]

# must invoke with environment "berkepar"
# adjunct_island,determiner_noun_agreement_with_adjective_1,intransitive,principle_A_case_1,tough_vs_raising_1,anaphor_gender_agreement,determiner_noun_agreement_with_adj_irregular_1,irregular_past_participle_adjectives,principle_A_case_2,tough_vs_raising_2,anaphor_number_agreement,determiner_noun_agreement_with_adj_irregular_2,irregular_past_participle_verbs,principle_A_c_command,transitive,animate_subject_passive,distractor_agreement_relational_noun
# irregular_plural_subject_verb_agreement_1,principle_A_domain_1,wh_island,animate_subject_trans,distractor_agreement_relative_clause,irregular_plural_subject_verb_agreement_2,principle_A_domain_2,wh_questions_object_gap,causative,drop_argument,left_branch_island_echo_question,principle_A_domain_3,wh_questions_subject_gap,complex_NP_island,ellipsis_n_bar_1,left_branch_island_simple_question,principle_A_reconstruction
# wh_questions_subject_gap_long_distance,coordinate_structure_constraint_complex_left_branch,ellipsis_n_bar_2,matrix_question_npi_licensor_present,regular_plural_subject_verb_agreement_1,wh_vs_that_no_gap,coordinate_structure_constraint_object_extraction,existential_there_object_raising,npi_present_1,regular_plural_subject_verb_agreement_2,wh_vs_that_no_gap_long_distance,determiner_noun_agreement_1,existential_there_quantifiers_1,npi_present_2,sentential_negation_npi_licensor_present,wh_vs_that_with_gap,determiner_noun_agreement_2
# existential_there_quantifiers_2,only_npi_licensor_present,sentential_negation_npi_scope,wh_vs_that_with_gap_long_distance,determiner_noun_agreement_irregular_1,existential_there_subject_raising,only_npi_scope,sentential_subject_island,determiner_noun_agreement_irregular_2,expletive_it_object_raising,passive_1,superlative_quantifiers_1,determiner_noun_agreement_with_adj_2,inchoative,passive_2,superlative_quantifiers_2

# export HF_ENDPOINT=https://hf-mirror.com
# export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
nvidia-smi
input_str="$1"
echo $input_str
python parse_testblimp.py --input_list $input_str

