run_name: TGTree_500M
seed: 6198
epoch: null
dry_run: false
workspace: /data/home/scyb223/TG-Interpolation
finetune_task: null
model:
  d_model: 1408
  n_heads: 16
  n_kv_heads: null
  clip_qkv: null
  n_layers: 16
  mlp_ratio: 8
  mlp_hidden_size: null
  activation_type: swiglu
  block_type: sequential
  block_group_size: 1
  alibi: false
  alibi_bias_max: 8.0
  rope: true
  rope_full_precision: true
  rope_theta: 500000
  flash_attention: true
  flex_attention: false
  attention_dropout: 0.0
  multi_query_attention: null
  attention_layer_norm: false
  residual_dropout: 0.0
  embedding_dropout: 0.0
  embedding_layer_norm: false
  layer_norm_type: rms
  layer_norm_with_affine: true
  layer_norm_eps: 1.0e-06
  attention_layer_norm_with_affine: false
  max_sequence_length: 2048
  include_bias: true
  bias_for_layer_norm: true
  scale_logits: false
  vocab_size: 50320
  embedding_size: 50320
  weight_tying: true
  eos_token_id: 50256
  pad_token_id: 50258
  init_device: cuda
  init_fn: normal
  init_std: 0.02
  init_cutoff_factor: 3.0
  precision: amp_bf16
  scale_emb_init: false
  emb_init_std: null
  norm_after: false
  transformer_grammar_type: tree
  mix_head_type: []
  tg_proximal_k: 20
  tg_height_h: 5
optimizer:
  name: adamw
  learning_rate: 0.001866
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08
  no_decay_norm_and_bias: null
  selective_updates: false
  decay_norm_and_bias: true
  decay_embeddings: false
  metrics_log_interval: 10
  record_update_metrics: false
scheduler:
  name: cosine_with_warmup
  units: steps
  t_warmup: 2000
  t_max: null
  alpha_f: 0.1
  min_lr: 1.0e-05
  grad_clip_warmup_steps: null
  grad_clip_warmup_factor: null
  warmup_min_lr: 0.0
data:
  paths:
  - /dev/shm/dataset/bbc-news/tg/train.npy
  memmap_dtype: uint16
  datasets: null
  label_mask_paths: null
  pad_direction: right
  generate_attention_mask: false
  generate_doc_lengths: false
  num_workers: 4
  drop_last: true
  pin_memory: true
  prefetch_factor: 8
  persistent_workers: true
  timeout: 0
  seed: null
  instance_filter: null
restore_dataloader: true
fast_forward_batches: null
evaluators:
- label: TG-ppl-validation
  type: lm
  data:
    paths:
    - /dev/shm/dataset/bbc-news/tg/dev.npy
    memmap_dtype: uint16
    datasets: null
    label_mask_paths: null
    pad_direction: right
    generate_attention_mask: false
    generate_doc_lengths: false
    num_workers: 1
    drop_last: false
    pin_memory: true
    prefetch_factor: 1
    persistent_workers: false
    timeout: 0
    seed: null
    instance_filter: null
  device_eval_batch_size: null
  subset_num_batches: null
- label: TG-ppl-validation-test
  type: lm
  data:
    paths:
    - /dev/shm/dataset/bbc-news/tg/test.npy
    memmap_dtype: uint16
    datasets: null
    label_mask_paths: null
    pad_direction: right
    generate_attention_mask: false
    generate_doc_lengths: false
    num_workers: 1
    drop_last: false
    pin_memory: true
    prefetch_factor: null
    persistent_workers: false
    timeout: 0
    seed: null
    instance_filter: null
  device_eval_batch_size: null
  subset_num_batches: null
eval_interval: 1000
tokenizer:
  identifier: /dev/shm/dataset/bbc-news/TG_GPT2_tokenizer.json
  truncate_direction: right
  vocabulary: /dev/shm/dataset/bbc-news/TG_GPT2_tokenizer.json
save_folder: /data/home/scyb223/TG-Interpolation/saved_models/TGTree_500M
remote_save_folder: null
canceled_check_interval: 50
save_interval: 10000
save_interval_unsharded: 10000
save_interval_ephemeral: null
save_num_checkpoints_to_keep: 0
save_num_unsharded_checkpoints_to_keep: 1
save_overwrite: true
force_save_unsharded: false
no_pre_train_checkpoint: false
load_path: null
load_path_sharded_checkpointer: null
try_load_latest_save: false
reset_optimizer_state: false
reset_trainer_state: false
sharded_checkpointer: torch_legacy
new_style_checkpoints: null
max_duration: 1ep
global_train_batch_size: 280
device_train_batch_size: 35
device_train_microbatch_size: 16
device_eval_batch_size: 16
eval_subset_num_batches: -1
eval_on_load: false
eval_return: false
eval_no_save: false
device_train_grad_accum: 2
max_grad_norm: 1.0
max_grad_norm_ratio: null
precision: amp_bf16
wandb:
  project: TG-bbcnews
  entity: qlwpc-shanghaitech-university
  group: null
  name: TGTree_500M
  tags:
  - watching
  log_artifacts: false
  rank_zero_only: true
  log_interval: 1
speed_monitor:
  window_size: 1
  gpu_flops_available: null
console_log_interval: 1
gen1_gc_interval: 10
compile:
  mode: default
  fullgraph: false
  backend: inductor
  dynamic: null
distributed_strategy: ddp
fsdp:
  use_orig_params: true
  sharding_strategy: SHARD_GRAD_OP
  wrapping_strategy: null
  precision: mixed
  hybrid_sharding_num_model_replicas: null
ddp:
  grad_sync_mode: batch
  find_unused_params: false
softmax_auxiliary_loss: false
auxiliary_loss_multiplier: 0.0001
time_limit: null
extra_steps_after_cancel: 10
early_stopping_factor: null
save_data_indices: true
python_profiling: false
torch_profiling: false
stop_at: 55863
stop_after: null
activation_checkpointing: null
fused_loss: null
hf_datasets_cache_dir: null
module_outputs_save_steps: null
